ALTER TABLE plugins ADD COLUMN IF NOT EXISTS display_name VARCHAR(500);
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS endpoints JSONB NOT NULL DEFAULT '[]';
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS documentation JSONB NOT NULL DEFAULT '[]';
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS settings_schema JSONB NOT NULL DEFAULT '{}';
ALTER TABLE plugins ADD COLUMN IF NOT EXISTS settings JSONB NOT NULL DEFAULT '{}';
