/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityTimeline: typeof import('./src/components/ActivityTimeline.vue')['default']
    AggregateResults: typeof import('./src/components/AggregateResults.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardsView: typeof import('./src/components/CardsView.vue')['default']
    CardsViewSettings: typeof import('./src/components/CardsViewSettings.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CollectionNameLabel: typeof import('./src/components/CollectionNameLabel.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DocsViewer: typeof import('./src/components/DocsViewer.vue')['default']
    DynamicFormField: typeof import('./src/components/DynamicFormField.vue')['default']
    EditDialog: typeof import('./src/components/MenuBuilder/EditDialog.vue')['default']
    EditItemModal: typeof import('./src/components/EditItemModal.vue')['default']
    FieldNameLabel: typeof import('./src/components/FieldNameLabel.vue')['default']
    FieldSelector: typeof import('./src/components/FieldSelector.vue')['default']
    FilterBuilder: typeof import('./src/components/FilterBuilder.vue')['default']
    FilterGroupComponent: typeof import('./src/components/FilterGroupComponent.vue')['default']
    FilterRuleComponent: typeof import('./src/components/FilterRuleComponent.vue')['default']
    FilterValueInput: typeof import('./src/components/FilterValueInput.vue')['default']
    FormFieldRenderer: typeof import('./src/components/FormFieldRenderer.vue')['default']
    IconPicker: typeof import('./src/components/inputs/IconPicker.vue')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    InstanceDetailDrawer: typeof import('./src/components/InstanceDetailDrawer.vue')['default']
    InstanceLogsDrawer: typeof import('./src/components/InstanceLogsDrawer.vue')['default']
    KanbanView: typeof import('./src/components/KanbanView.vue')['default']
    KanbanViewSettings: typeof import('./src/components/KanbanViewSettings.vue')['default']
    KeysDrawer: typeof import('./src/components/developerSettings/keysDrawer.vue')['default']
    LogDetailPopup: typeof import('./src/components/LogDetailPopup.vue')['default']
    Message: typeof import('primevue/message')['default']
    MetricCard: typeof import('./src/components/MetricCard.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    PluginRow: typeof import('./src/components/PluginRow.vue')['default']
    PluginSandbox: typeof import('./src/components/PluginSandbox.vue')['default']
    ProgressBar: typeof import('primevue/progressbar')['default']
    QuickAddMenuItems: typeof import('./src/components/MenuBuilder/QuickAddMenuItems.vue')['default']
    QuickAddModal: typeof import('./src/components/QuickAddModal.vue')['default']
    QuickCreateDialog: typeof import('./src/components/QuickCreateDialog.vue')['default']
    RecordForm: typeof import('./src/components/RecordForm.vue')['default']
    RelationalDrawer: typeof import('./src/components/RelationalDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaErDiagram: typeof import('./src/components/SchemaErDiagram.vue')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Sidebar: typeof import('primevue/sidebar')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    TableView: typeof import('./src/components/TableView.vue')['default']
    TableViewSettings: typeof import('./src/components/TableViewSettings.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    TemplateInput: typeof import('./src/components/TemplateInput.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToastContainer: typeof import('./src/components/ToastContainer.vue')['default']
    ViewRenderer: typeof import('./src/components/ViewRenderer.vue')['default']
    ViewSelector: typeof import('./src/components/ViewSelector.vue')['default']
    ViewSettingsDrawer: typeof import('./src/components/ViewSettingsDrawer.vue')['default']
  }
}
