apiVersion: v1
kind: Secret
metadata:
  name: core-secrets
  namespace: plugin-core
type: Opaque
stringData:
  REGISTRY_ENCRYPTION_KEY: "UuG5d1HEJuBH0tElr6R4I3deq/BabTiHhfByFS9xom4="
  POSTGRES_PASSWORD: "postgres"
  ADMIN_EMAIL: "admin@alcedo.dev"
  ADMIN_PASSWORD: "admin123!"
