apiVersion: v1
kind: Service
metadata:
  name: plugin-core
  namespace: plugin-core
  labels:
    app.kubernetes.io/name: plugin-core
spec:
  selector:
    app: plugin-core
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
