apiVersion: v1
kind: Service
metadata:
    name: alcedocore
    namespace: alcedocore
    labels:
        app.kubernetes.io/name: alcedocore
spec:
    selector:
        app: alcedocore
    ports:
        - port: 8080
          targetPort: 8080
          name: http
    type: ClusterIP
