apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: plugin-data
    namespace: alcedocore
    labels:
        app.kubernetes.io/name: alcedocore
        app.kubernetes.io/managed-by: alcedocore
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
