apiVersion: apps/v1
kind: Deployment
metadata:
    name: plugin-hello-world
    namespace: alcedocore
    labels:
        app.kubernetes.io/name: hello-world
        app.kubernetes.io/part-of: plugin-hello-world
        app.kubernetes.io/managed-by: alcedocore
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/part-of: plugin-hello-world
    template:
        metadata:
            labels:
                app.kubernetes.io/part-of: plugin-hello-world
                app.kubernetes.io/managed-by: alcedocore
        spec:
            containers:
                - name: hello-world
                  image: localhost:5000/hello-world:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
                        name: http
                  env:
                      - name: PORT
                        value: "8080"
---
apiVersion: v1
kind: Service
metadata:
    name: plugin-hello-world
    namespace: alcedocore
    labels:
        app.kubernetes.io/name: hello-world
        app.kubernetes.io/part-of: plugin-hello-world
spec:
    selector:
        app.kubernetes.io/part-of: plugin-hello-world
    ports:
        - port: 80
          targetPort: 8080
          name: http
    type: ClusterIP
