apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    name: alcedocore
    namespace: alcedocore
    labels:
        app.kubernetes.io/name: alcedocore
        app.kubernetes.io/managed-by: alcedocore
spec:
    minAvailable: 1
    selector:
        matchLabels:
            app: alcedocore
