<script setup lang="ts">
import { ref, onMounted } from "vue";

const loading = ref(true);
const data = ref(null);

onMounted(async () => {
    try {
        // Replace with your actual API call:
        // data.value = await sdk.fetch('/api/test-page')
        data.value = { status: "ready", page: "test-page" };
    } catch (e) {
        console.error("Failed to load page data", e);
    } finally {
        loading.value = false;
    }
});
</script>

<template>
    <div class="alcedo-test-page-page">
        <div v-if="loading" class="loading">Loading...</div>
        <div v-else-if="data" class="content">
            <h1>TestPage</h1>
            <p>
                This page was generated by
                <code>alcedo add page test-page</code>.
            </p>
            <!-- Register this page in pages/main.ts: import and add to the pages array -->
            <pre>{{ data }}</pre>
        </div>
    </div>
</template>

<style scoped>
.alcedo-test-page-page {
    padding: 1.5rem;
}
.loading {
    color: var(--text-muted);
    padding: 2rem;
    text-align: center;
}
.content {
    max-width: 800px;
}
h1 {
    margin-bottom: 1rem;
}
pre {
    background: var(--bg-code, #f5f5f5);
    padding: 1rem;
    border-radius: 4px;
    overflow-x: auto;
}
</style>
